stages:
  - Acceptance Tests

# Job Linux Fedora - execução dos testes sem docker
WEB Testing in Chrome:
    stage: Acceptance Tests
    image: fedora:31
    tags:
        - docker
    artifacts:
        when: always
        paths:
            - ./results
        expire_in: 1 week
    before_script:
        - cat /etc/*-release
        - dnf upgrade -y >/dev/null && echo OK
        - dnf install -y python37 >/dev/null && echo OK
        - dnf install -y chromedriver >/dev/null && echo OK
        - dnf install -y https://chromedriver.storage.googleapis.com/2.28/chromedriver_linux64.zip
        # - dnf install -y http://dist.control.lth.se/public/Fedora-31/x86_64/google.x86_64/google-chrome-beta-86.0.4240.30-1.x86_64.rpm >/dev/null && echo OK        
        # - dnf install -y https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm >/dev/null && echo OK
        - chown root /usr/bin/chromedriver >/dev/null && echo OK
        - chmod +x /usr/bin/chromedriver >/dev/null && echo OK
        - chmod 755 /usr/bin/chromedriver >/dev/null && echo OK
        - chrome --version
        - chromedriver --version
        - python --version
        - pip3 install robotframework robotframework-seleniumlibrary | grep "Successfully installed"
    script:
        - robot -d ./results -v BROWSER:headlesschrome TestSitePractice.robot

# Job Docker - execução dos testes em container Docker
WEB Testing in Chrome and Docker:
    stage: Acceptance Tests
    image: registry.gitlab.com/myrobotprojects/mydockerimages:latest
    tags:
        - docker
    artifacts:
        when: always
        paths:
            - ./results
        expire_in: 1 week
    script:
        - robot -d ./results -v BROWSER:headlesschrome TestSitePractice.robot
