stages:
  - Acceptance Tests

# Job Linux Fedora - execução dos testes sem docker
WEB Testing in Chrome:
    stage: Acceptance Tests
    image: fedora:31
    tags:
        - docker
    artifacts:
        when: always
        paths:
            - ./results
        expire_in: 1 week
    before_script:
        - cat /etc/*-release
        - dnf upgrade -y >/dev/null && echo OK
        - dnf install -y python37 >/dev/null && echo OK
        - dnf install -y https://download-ib01.fedoraproject.org/pub/fedora/linux/development/rawhide/Everything/x86_64/os/Packages/c/chromium-common-88.0.4324.96-1.fc34.x86_64.rpm >/dev/null && echo OK
        - dnf install -y https://download-ib01.fedoraproject.org/pub/fedora/linux/development/rawhide/Everything/x86_64/os/Packages/c/chromedriver-88.0.4324.96-1.fc34.x86_64.rpm >/dev/null && echo OK
        - dnf install -y https://dl.google.com/linux/chrome/rpm/stable/x86_64/google-chrome-stable-88.0.4324.96-1.x86_64.rpm >/dev/null && echo OK
        - chown root /usr/bin/chromedriver >/dev/null && echo OK
        - chmod +x /usr/bin/chromedriver >/dev/null && echo OK
        - chmod 755 /usr/bin/chromedriver >/dev/null && echo OK
        - chromedriver --version
        - python --version
        - pip3 install robotframework robotframework-seleniumlibrary | grep "Successfully installed"
    script:
        - robot -d ./results -v BROWSER:headlesschrome TestSitePractice.robot

# Job Docker - execução dos testes em container Docker
WEB Testing in Chrome and Docker:
    stage: Acceptance Tests
    image: registry.gitlab.com/myrobotprojects/mydockerimages:latest
    tags:
        - docker
    artifacts:
        when: always
        paths:
            - ./results
        expire_in: 1 week
    script:
        - robot -d ./results -v BROWSER:headlesschrome TestSitePractice.robot
